language: objective-c
osx_image: xcode10

before_install:
  - gem install cocoapods -v '0.32.1'

script:
    - xcodebuild clean test -workspace Payculator.xcworkspace -scheme Payculator -destination "platform=iOS Simulator,name=iPhone 8,OS=11.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

after_success:

# safelist
branches:
  only:
  - master
  - Development
